import pygame
from enum import Enum

WIDTH = 1280
HEIGHT = 720

SCREEN = pygame.display.set_mode((WIDTH, HEIGHT))

CLOCK = pygame.time.Clock()
CAPTION = "Tic Tac Toe"

SIZE_FONT = 60

BOARD_SIZE = 5
AMMOUNT_TO_WIN = 3

CELLS_AMMOUNT = BOARD_SIZE ** 2

CELL_WIDTH = WIDTH // BOARD_SIZE
CELL_HEIGHT = HEIGHT // BOARD_SIZE

X_SIZE = 250 // BOARD_SIZE
O_SIZE = 250 // BOARD_SIZE

X_WIDTH = 10
LINE_WIDTH = 10
CIRCLE_WIDTH = 10

CORRECTIVE_VAL_TEXT_WIDTH_1 = 100
CORRECTIVE_VAL_TEXT_HEIGHT_1 = 30

FRAMERATE = 60


class COLORS(Enum):
    BLACK = (0, 0, 0)

    LINE_COLOR = (255, 255, 255)

    X_COLOR = (255, 0, 0)

    O_COLOR = (0, 0, 255)

    TEXT_COLOR = (255, 255, 0)
